# Generated by Django 4.1.2 on 2022-11-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
