# Generated by Django 4.1.2 on 2022-11-10 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_user', '0002_platformuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='platform_user',
        ),
        migrations.AddField(
            model_name='platformuser',
            name='address',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='platform_user.address'),
            preserve_default=False,
        ),
    ]
