# Generated by Django 4.1.2 on 2022-11-10 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('platform_user', '0004_remove_platformuser_address_address_platform_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformuser',
            name='django_user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='platform_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
