# Generated by Django 4.1.2 on 2022-11-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('platform_user', '0005_platformuser_django_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='platform_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_address', to='platform_user.platformuser'),
        ),
    ]
