# Generated by Django 4.1.2 on 2022-11-08 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platform_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.CharField(max_length=200)),
                ('pick_up_date', models.DateField()),
                ('pick_up_time', models.TimeField()),
                ('pick_up_place', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='platform_user.address')),
                ('shared_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_product', to='platform_user.platformuser')),
            ],
        ),
    ]
