# Generated by Django 4.1.2 on 2022-11-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='status_of_availability',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
